version: '3'
services:
  db:
    image: mariadb:10.5.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_USER: root
    ports:
      - 3307:3306
    volumes:
      - popcorn-data:/var/lib/mysql

volumes:
  popcorn-data:

networks:
  popcorn_network:
    driver: bridge