CREATE DATABASE popcorn;
USE popcorn;

CREATE TABLE IF NOT EXISTS `movies` (
  `id` BINARY(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `rating` VARCHAR(8) NOT NULL,
  `launch_date` TIMESTAMP NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  INDEX(`name`),

  CONSTRAINT `movies_pk` PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `actors` (
  `id` BINARY(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  INDEX(`name`),

  CONSTRAINT `cast_pk` PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `directors` (
  `id` BINARY(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  INDEX(`name`),

  CONSTRAINT `directors_pk` PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `movies_actors` (
  `id` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `movie_id` BINARY(36) NOT NULL,
  `actor_id` BINARY(36) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (`movie_id`) REFERENCES movies(`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (`actor_id`) REFERENCES actors(`id`) ON UPDATE CASCADE ON DELETE RESTRICT,

  CONSTRAINT `movies_actors_pk` PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `movies_directors` (
  `id` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `movie_id` BINARY(36) NOT NULL,
  `director_id` BINARY(36) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (`movie_id`) REFERENCES movies(`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (`director_id`) REFERENCES directors(`id`) ON UPDATE CASCADE ON DELETE RESTRICT,

  CONSTRAINT `movies_directors_pk` PRIMARY KEY (`id`)
);